# Generated by Django 4.1.7 on 2023-04-24 09:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
